services:

  gateway:
    image: ccr.ccs.tencentyun.com/kratos/gateway:v1.7.0
    ports:
      - "8080:8080"
    container_name: ecommerce-gateway
    platform: linux/amd64
    pull_policy: always
    restart: on-failure:3
    environment:
      - CASDOOR_URL=http://CASDOOR_URL:8000
      - DISCOVERY_DSN=consul://DISCOVERY_DSN:3026
      - DISCOVERY_CONFIG_PATH=ecommerce/gateway/config.yaml
      - POLICIES_FILE_PATH=/app/dynamic-config/policies/policies.csv
      - MODEL_FILE_PATH=/app/dynamic-config/policies/model.conf
    command:
      - "/app/gateway"
      - "-conf"
      - "/app/configs/config.yaml"
    networks:
      - ecommerce

# docker compose build
