// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: gateway/middleware/routerfilter/v1/routerfilter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Rule) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RouterFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterFilter) Reset() {
	*x = RouterFilter{}
	mi := &file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterFilter) ProtoMessage() {}

func (x *RouterFilter) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterFilter.ProtoReflect.Descriptor instead.
func (*RouterFilter) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescGZIP(), []int{1}
}

func (x *RouterFilter) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_gateway_middleware_routerfilter_v1_routerfilter_proto protoreflect.FileDescriptor

var file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDesc = string([]byte{
	0x0a, 0x35, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x34, 0x0a, 0x04, 0x52,
	0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x73, 0x22, 0x4e, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x3e, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x2d, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x69,
	0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescOnce sync.Once
	file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescData []byte
)

func file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescGZIP() []byte {
	file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDesc), len(file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDesc)))
	})
	return file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDescData
}

var file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_middleware_routerfilter_v1_routerfilter_proto_goTypes = []any{
	(*Rule)(nil),         // 0: gateway.middleware.routerfilter.v1.Rule
	(*RouterFilter)(nil), // 1: gateway.middleware.routerfilter.v1.RouterFilter
}
var file_gateway_middleware_routerfilter_v1_routerfilter_proto_depIdxs = []int32{
	0, // 0: gateway.middleware.routerfilter.v1.RouterFilter.rules:type_name -> gateway.middleware.routerfilter.v1.Rule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_middleware_routerfilter_v1_routerfilter_proto_init() }
func file_gateway_middleware_routerfilter_v1_routerfilter_proto_init() {
	if File_gateway_middleware_routerfilter_v1_routerfilter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDesc), len(file_gateway_middleware_routerfilter_v1_routerfilter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_routerfilter_v1_routerfilter_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_routerfilter_v1_routerfilter_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_routerfilter_v1_routerfilter_proto_msgTypes,
	}.Build()
	File_gateway_middleware_routerfilter_v1_routerfilter_proto = out.File
	file_gateway_middleware_routerfilter_v1_routerfilter_proto_goTypes = nil
	file_gateway_middleware_routerfilter_v1_routerfilter_proto_depIdxs = nil
}
