# This is a gateway config.
name: gateway
version: v1
middlewares:

  # 前端跨域选项
  - name: cors
    options:
      '@type': type.googleapis.com/gateway.middleware.cors.v1.Cors
      allowCredentials: true
      allowHeaders:
        - Authorization
        - Content-Type
        - X-Requested-With
        - DNT
        - Sec-Fetch-Dest
        - Sec-Fetch-Mode
        - Sec-Fetch-Site
      allowOrigins:
        - http://localhost:3000
        - localhost:3000
        - .apikv.com
      allowMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
  - name: logging
  - name: tracing
    options:
      '@type': type.googleapis.com/gateway.middleware.tracing.v1.Tracing
      httpEndpoint: '99.suyiiyii.top:3003' # default opentelemetry collector port
      insecure: true # http方式
  - name: transcoder
  - name: jwt
    # 不需要鉴权的接口
    router_filter:
      rules:
        - path: /v1/categories/*
          methods:
            - GET
            - OPTIONS
        - path: /v1/products
          methods:
            - GET
            - OPTIONS
        - path: /v1/auth
          methods:
            - OPTIONS
            - POST
        - path: /v1/payments/notify
          methods:
            - OPTIONS
            - POST
        - path: /v1/payments/callback
          methods:
            - OPTIONS
            - POST
    # 基于用户的接口权限控制
  - name: rbac
    # 不需要鉴权的接口
    router_filter:
      rules:
        - path: /v1/categories/*
          methods:
            - GET
            - OPTIONS
        - path: /v1/products
          methods:
            - GET
            - OPTIONS
        - path: /v1/auth
          methods:
            - OPTIONS
            - POST
        - path: /v1/payments/notify
          methods:
            - OPTIONS
            - POST
        - path: /v1/payments/callback
          methods:
            - OPTIONS
            - POST

endpoints:

  - path: /v1/auth*
    timeout: 1s
    description: "Get user information"
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-auth-v1'
        weight: 100
        health_check: { }
    retry:
      attempts: 3
      per_try_timeout: "7s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"

  - path: /v1/users*
    timeout: 1s
    description: "Get user information"
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-user-v1'
        weight: 100
        health_check: { }
    retry:
      attempts: 3
      per_try_timeout: "7s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"

#  - path: /v1/products*
#    timeout: 1s
#    protocol: HTTP
#    backends:
#      - target: 'discovery:///ecommerce-product-v1'
#    retry:
#      attempts: 3
#      per_try_timeout: "7s"
#      conditions:
#        - by_status_code: "500-599"
#        - by_header:
#            name: "grpc-status"
#            value: "14"
#    metadata:
#      cache: "true"

  - path: /v1/categories*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-category-v1'
    retry:
      attempts: 3
      per_try_timeout: "7s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"

#  - path: /v1/orders*
#    timeout: 1s
#    protocol: HTTP
#    backends:
#      - target: 'discovery:///ecommerce-order-v1'
#    retry:
#      attempts: 3
#      per_try_timeout: "7s"
#      conditions:
#        - by_status_code: "500-599"
#        - by_header:
#            name: "grpc-status"
#            value: "14"
#
#  - path: /v1/payments*
#    timeout: 1s
#    protocol: HTTP
#    backends:
#      - target: 'discovery:///ecommerce-payment-v1'
#    retry:
#      attempts: 3
#      per_try_timeout: "7s"
#      conditions:
#        - by_status_code: "500-599"
#        - by_header:
#            name: "grpc-status"
#            value: "14"

#    metadata:
#      cache: "true"

#  - path: /api.order.v1.OrderService
#    method: POST
#    timeout: 1s
#    protocol: GRPC
#    backends:
#      # - target: '127.0.0.1:9000'
#      - target: 'discovery:///ecommerce-order-v1'
#    retry:
#      attempts: 3
#      perTryTimeout: 0.1s
#      conditions:
#        - byStatusCode: '502-504'
#        - byHeader:
#            name: 'Grpc-Status'
#            value: '14'
