# This is a gateway config.
name: gateway
version: v1
middlewares:
  - name: tracing
    options:
      '@type': type.googleapis.com/gateway.middleware.tracing.v1.Tracing
      httpEndpoint: '99.suyiiyii.top:3003' # default opentelemetry collector port
      insecure: true # http方式
  - name: "auth"
    options:
      "@type": "type.googleapis.com/google.protobuf.StringValue"
      value: "token"
    required: true
  - name: logging
  - name: jwt
  #  - name: rbac
  - name: transcoder
  - name: cors
    options:
      '@type': type.googleapis.com/gateway.middleware.cors.v1.Cors
      allowCredentials: true
      allowOrigins:
        - http://localhost:3000
        - http://localhost:443
        - .apikv.com
      allowMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS

endpoints:

  - path: /v1/users*
    timeout: 1s
    description: "Get user information"
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-user-v1'
        weight: 100
        health_check: { }
    retry:
      attempts: 3
      per_try_timeout: "2s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"

  - path: /v1/products*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-product-v1'
    retry:
      attempts: 3
      per_try_timeout: "2s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"

  - path: /v1/categories*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-category-v1'
    retry:
      attempts: 3
      per_try_timeout: "2s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"

  - path: /v1/orders*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-order-v1'
    retry:
      attempts: 3
      per_try_timeout: "2s"
      conditions:
        - by_status_code: "500-599"
        - by_header:
            name: "grpc-status"
            value: "14"
    metadata:
      cache: "true"
