# This is a gateway config.
name: gateway
version: v1
middlewares:
  - name: tracing
    options:
      '@type': type.googleapis.com/gateway.middleware.tracing.v1.Tracing
      httpEndpoint: '99.suyiiyii.top:3002' # default opentelemetry collector port
  - name: logging
  - name: jwt
  #  - name: rbac
  - name: transcoder
  - name: cors
    options:
      '@type': type.googleapis.com/gateway.middleware.cors.v1.Cors
      allowCredentials: true
      allowOrigins:
        - .google.com
      allowMethods:
        - GET
        - POST
        - OPTIONS
endpoints:
  # 商品微服务
  - path: /v1/products
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-product-v1'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: { "success": 0.6, "request": "1", "bucket": "10", "window": "3s" }
          backupService: { "endpoint": { "backends": [ { "target": "127.0.0.1:8001" } ] } }
          assertCondtions:
            - { "by_status_code": "200" }
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite

  - path: /v1/products/*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-product-v1'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: { "success": 0.6, "request": "1", "bucket": "10", "window": "3s" }
          backupService: { "endpoint": { "backends": [ { "target": "127.0.0.1:8001" } ] } }
          assertCondtions:
            - { "by_status_code": "200" }
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite

  # 分类微服务
  - path: /v1/categories
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-category-v1'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: { "success": 0.6, "request": "1", "bucket": "10", "window": "3s" }
          backupService: { "endpoint": { "backends": [ { "target": "127.0.0.1:8001" } ] } }
          assertCondtions:
            - { "by_status_code": "200" }
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite

  - path: /v1/categories/*
    timeout: 1s
    protocol: HTTP
    backends:
      - target: 'discovery:///ecommerce-category-v1'
    middlewares:
      - name: circuitbreaker
        options:
          '@type': type.googleapis.com/gateway.middleware.circuitbreaker.v1.CircuitBreaker
          successRatio: { "success": 0.6, "request": "1", "bucket": "10", "window": "3s" }
          backupService: { "endpoint": { "backends": [ { "target": "127.0.0.1:8001" } ] } }
          assertCondtions:
            - { "by_status_code": "200" }
      - name: rewrite
        options:
          '@type': type.googleapis.com/gateway.middleware.rewrite.v1.Rewrite
